services:
  - type: web
    name: niya-backend
    runtime: docker
    dockerfilePath: ./back-end/Dockerfile
    dockerContext: ./back-end
    plan: free
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_SERVE_STATIC_FILES
        value: "true"
      - key: RAILS_LOG_TO_STDOUT
        value: "true"
      - key: STORAGE_SERVICE
        value: cloudflare
      - key: SECRET_KEY_BASE
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: API_KEY
        sync: false
      - key: VIDEOSDK_SECRET_KEY
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: R2_ACCESS_KEY_ID
        sync: false
      - key: R2_SECRET_ACCESS_KEY
        sync: false
      - key: R2_BUCKET
        sync: false
      - key: R2_ENDPOINT
        sync: false
