services:
  - type: web
    name: niya-backend
    runtime: docker
    dockerfilePath: ./back-end/Dockerfile
    dockerContext: ./back-end
    plan: free
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_SERVE_STATIC_FILES
        value: "true"
      - key: RAILS_LOG_TO_STDOUT
        value: "true"
      - key: STORAGE_SERVICE
        value: cloudflare
      - key: SECRET_KEY_BASE
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: API_KEY
        sync: false
      - key: VIDEOSDK_SECRET_KEY
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: R2_ACCESS_KEY_ID
        sync: false
      - key: R2_SECRET_ACCESS_KEY
        sync: false
      - key: R2_BUCKET
        sync: false
      - key: R2_ENDPOINT
        sync: false

  - type: web
    name: niya-practice
    runtime: docker
    dockerfilePath: ./niya-practice/Dockerfile
    dockerContext: ./niya-practice
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: MYSQL_HOST
        value: gateway01.ap-southeast-1.prod.aws.tidbcloud.com
      - key: MYSQL_PORT
        value: "4000"
      - key: MYSQL_USER
        value: 3awQN3VvrGtuU5E.root
      - key: MYSQL_DATABASE
        value: niya_admin_db
      - key: MYSQL_POOL_SIZE
        value: "10"
      - key: NEXT_PUBLIC_APP_URL
        value: https://practice.niya.app
      - key: NEXT_PUBLIC_NIYA_URL
        value: https://niya.app
      - key: NEXTAUTH_URL
        value: https://practice.niya.app
      - key: AZURE_TTS_REGION
        value: centralindia
      - key: AZURE_TRANSLATOR_REGION
        value: centralindia
      - key: MYSQL_PASSWORD
        sync: false
      - key: NEXTAUTH_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: MICROSOFT_CLIENT_ID
        sync: false
      - key: MICROSOFT_CLIENT_SECRET
        sync: false
      - key: AZURE_TTS_KEY
        sync: false
      - key: AZURE_TRANSLATOR_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: SARVAM_API_KEY
        sync: false
      - key: GOOGLE_SA_KEY
        sync: false
      - key: ADMIN_EMAILS
        sync: false
